name: Update VPM Dependencies

on: 
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

jobs:
  upgrade-vpm-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install vrc-get
        uses: anatawa12/sh-actions/setup-vrc-get@master
      
      - name: Add VPM Repos URLs
        run: |
          vrc-get repo add https://vpm.nadena.dev/vpm.json && \
          vrc-get repo add https://vpm.anatawa12.com/vpm.json && \
          vrc-get repo add https://vpm.rs64.net/vpm.json && \
          vrc-get repo add https://narazaka.github.io/AvatarMenuCreaterForMA/index.json && \
          vrc-get repo add https://vpm.dreadscripts.com/listings/main.json && \
          echo Install done

      - name: Check if there is VPM updates
        id: check-outdated
        run: |
          OUTDATED_OUTPUT=$(vrc-get outdated)
          echo $OUTDATED_OUTPUT
          echo "OUTDATED_OUTPUT=$OUTDATED_OUTPUT" >> "$GITHUB_OUTPUT"

      - name: Upgrade all packages
        id: run-upgrade
        if: ${{ steps.check-outdated.outputs.OUTDATED_OUTPUT }} is not null
        run: |
          UPGRADE_OUTPUT=$(vrc-get upgrade -y)
          echo $UPGRADE_OUTPUT
          echo "UPGRADE_OUTPUT=$UPGRADE_OUTPUT" >> "$GITHUB_OUTPUT"
          
      - name: Commit changes
        if: ${{ steps.check-outdated.outputs.OUTDATED_OUTPUT }} is not null
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: |
            Auto - Upgrade VPM dependencies
            Outdated:
            ${{ steps.check-outdated.outputs.OUTDATED_OUTPUT }}
            Upgraded:
            ${{ steps.run-upgrade.outputs.UPGRADE_OUTPUT }}