name: Update VPM Dependencies

on: 
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

jobs:
  upgrade-vpm-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install vrc-get
        uses: anatawa12/sh-actions/setup-vrc-get@master
      
      - name: Add VPM Repos URLs
        run: |
          vrc-get repo add https://vpm.nadena.dev/vpm.json && \
          vrc-get repo add https://vpm.anatawa12.com/vpm.json && \
          vrc-get repo add https://vpm.rs64.net/vpm.json && \
          vrc-get repo add https://narazaka.github.io/AvatarMenuCreaterForMA/index.json && \
          vrc-get repo add https://vpm.dreadscripts.com/listings/main.json && \
          echo Install done

      - name: Check for VPM updates
        id: check-outdated
        run: |
          outdated_text=$(vrc-get outdated)
          echo $outdated_text
          {
            echo 'outdated_text<<EOF'
            echo $outdated_text
            echo EOF
          } >> "$GITHUB_OUTPUT"

      - name: Upgrade all packages
        id: run-upgrade
        if: ${{ steps.check-outdated.outputs.outdated_text != '' }}
        run: |
          upgrade_text=$(vrc-get upgrade -y)
          echo $upgrade_text
          {
            echo 'upgrade_text<<EOF'
            echo $upgrade_text
            echo EOF
          } >> "$GITHUB_OUTPUT"
          
      - name: Commit changes
        if: ${{ steps.check-outdated.outputs.outdated_text != '' }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: |
            Auto - Upgrade VPM dependencies
            Outdated:
            ${{ steps.check-outdated.outputs.outdated_text }}
            Upgraded:
            ${{ steps.check-outdated.outputs.upgrade_text }}